[package]
name = "ratatui-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
image = "0.25.8"
open = "5.3.2"
ratatui = { version = "0.29.0", features = ["unstable-rendered-line-info"] }
rayon = "1.11.0"
